// <auto-generated />
using System;
using API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UrlProject.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.ComplexUrl", b =>
                {
                    b.Property<string>("FullUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShortUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FullUrl", "ShortUrl");

                    b.HasIndex("UserId");

                    b.ToTable("ComplexUrls");

                    b.HasData(
                        new
                        {
                            FullUrl = "https://www.youtube.com/",
                            ShortUrl = "https://localhost:7212/s/41gHlq",
                            NumberOfUses = 0,
                            UserId = 2
                        },
                        new
                        {
                            FullUrl = "https://translate.google.com/?hl=iw&sl=en&tl=iw&op=translate",
                            ShortUrl = "https://localhost:7212/s/adw13q",
                            NumberOfUses = 0,
                            UserId = 1
                        },
                        new
                        {
                            FullUrl = "https://www.google.com/",
                            ShortUrl = "https://localhost:7212/s/add1sd",
                            NumberOfUses = 0
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Artur@gmail.com",
                            FirstName = "Artur",
                            LastName = "Krant",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Moshe@gmail.com",
                            FirstName = "Moshe",
                            LastName = "Levi",
                            Password = "857342"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Bob@gmail.com",
                            FirstName = "Bob",
                            LastName = "Dosomething",
                            Password = "098765"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Lebron@gmail.com",
                            FirstName = "Lebron",
                            LastName = "James",
                            Password = "847231"
                        },
                        new
                        {
                            Id = 5,
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("UrlProject.Logger.UrlUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UrlUsageLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IpAdress = "192.158.1.38",
                            ShortUrl = "https://localhost:7212/s/add1sd",
                            Time = new DateTime(2023, 3, 8, 20, 47, 7, 166, DateTimeKind.Local).AddTicks(5457)
                        },
                        new
                        {
                            Id = 2,
                            IpAdress = "192.158.1.38",
                            ShortUrl = "https://localhost:7212/s/adw13q",
                            Time = new DateTime(2023, 3, 8, 20, 47, 7, 166, DateTimeKind.Local).AddTicks(5503)
                        });
                });

            modelBuilder.Entity("API.Models.ComplexUrl", b =>
                {
                    b.HasOne("API.Models.User", null)
                        .WithMany("ComplexUrls")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("ComplexUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
